#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: AthenaLockedStyleNotification

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass AthenaLockedStyleNotification.AthenaLockedStyleNotification_C
// 0x0010 (0x0240 - 0x0230)
class UAthenaLockedStyleNotification_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0230(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UCommonTextBlock*                       DescriptionText;                                   // 0x0238(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void SetLockedStyleDescription(const class FText& LockedStyleDescription);
	void Construct();
	void ExecuteUbergraph_AthenaLockedStyleNotification(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"AthenaLockedStyleNotification_C">();
	}
	static class UAthenaLockedStyleNotification_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAthenaLockedStyleNotification_C>();
	}
};

}

