#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: B_ProjectileTrajectory_Athena_FireworksMortar

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BP_ProjectileTrajectory_Athena_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass B_ProjectileTrajectory_Athena_FireworksMortar.B_ProjectileTrajectory_Athena_FireworksMortar_C
// 0x0018 (0x02B0 - 0x0298)
class AB_ProjectileTrajectory_Athena_FireworksMortar_C final : public ABP_ProjectileTrajectory_Athena_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_B_ProjectileTrajectory_Athena_FireworksMortar_C; // 0x0298(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UArrowComponent*                        Arrow;                                             // 0x02A0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	float                                         YawOffset;                                         // 0x02A8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         MeshRotationOffset;                                // 0x02AC(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_B_ProjectileTrajectory_Athena_FireworksMortar(int32 EntryPoint);
	void SetTrajectorySpline(TArray<struct FVector>& SplinePoints, TArray<struct FVector>& SplineTangents);
	void ReceiveBeginPlay();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"B_ProjectileTrajectory_Athena_FireworksMortar_C">();
	}
	static class AB_ProjectileTrajectory_Athena_FireworksMortar_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AB_ProjectileTrajectory_Athena_FireworksMortar_C>();
	}
};

}

