#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: Border_BattlePass_Body_BG

#include "Basic.hpp"

#include "CommonUI_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Border_BattlePass_Body_BG.Border_BattlePass_Body_BG_C
// 0x0000 (0x00B0 - 0x00B0)
class UBorder_BattlePass_Body_BG_C final : public UCommonBorderStyle
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Border_BattlePass_Body_BG_C">();
	}
	static class UBorder_BattlePass_Body_BG_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBorder_BattlePass_Body_BG_C>();
	}
};

}

