#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: ButtonStyle_MobileCloseXHamburgerMenu

#include "Basic.hpp"

#include "ButtonStyle_MediumTransparentNoCues_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass ButtonStyle_MobileCloseXHamburgerMenu.ButtonStyle_MobileCloseXHamburgerMenu_C
// 0x0000 (0x0570 - 0x0570)
class UButtonStyle_MobileCloseXHamburgerMenu_C final : public UButtonStyle_MediumTransparentNoCues_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ButtonStyle_MobileCloseXHamburgerMenu_C">();
	}
	static class UButtonStyle_MobileCloseXHamburgerMenu_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UButtonStyle_MobileCloseXHamburgerMenu_C>();
	}
};

}

