#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: ButtonStyle_Skew_Desirable_AddFriend

#include "Basic.hpp"

#include "CommonUI_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass ButtonStyle-Skew_Desirable_AddFriend.ButtonStyle-Skew_Desirable_AddFriend_C
// 0x0000 (0x0570 - 0x0570)
class UButtonStyle_Skew_Desirable_AddFriend_C final : public UCommonButtonStyle
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ButtonStyle-Skew_Desirable_AddFriend_C">();
	}
	static class UButtonStyle_Skew_Desirable_AddFriend_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UButtonStyle_Skew_Desirable_AddFriend_C>();
	}
};

}

