#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: ChallengeProgressDisplay

#include "Basic.hpp"

#include "FortniteUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass ChallengeProgressDisplay.ChallengeProgressDisplay_C
// 0x0000 (0x0240 - 0x0240)
class UChallengeProgressDisplay_C final : public UAthenaChallengeProgressBar
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ChallengeProgressDisplay_C">();
	}
	static class UChallengeProgressDisplay_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UChallengeProgressDisplay_C>();
	}
};

}

