#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GA_CP_Props_S_Nature_h

#include "Basic.hpp"

#include "GA_Athena_Instance_PlaysetGrenadeWithTrajectory_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GA_CP_Props_S_Nature_h.GA_CP_Props_S_Nature_h_C
// 0x0000 (0x0C90 - 0x0C90)
class UGA_CP_Props_S_Nature_h_C final : public UGA_Athena_Instance_PlaysetGrenadeWithTrajectory_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GA_CP_Props_S_Nature_h_C">();
	}
	static class UGA_CP_Props_S_Nature_h_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_CP_Props_S_Nature_h_C>();
	}
};

}

