#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GE_Creative_Powerup_Jump

#include "Basic.hpp"

#include "GameplayAbilities_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GE_Creative_Powerup_Jump.GE_Creative_Powerup_Jump_C
// 0x0000 (0x05F0 - 0x05F0)
class UGE_Creative_Powerup_Jump_C final : public UGameplayEffect
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GE_Creative_Powerup_Jump_C">();
	}
	static class UGE_Creative_Powerup_Jump_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_Creative_Powerup_Jump_C>();
	}
};

}

