#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GE_ShadowBOmbLoop

#include "Basic.hpp"

#include "GameplayAbilities_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GE_ShadowBOmbLoop.GE_ShadowBombLoop_C
// 0x0000 (0x05F0 - 0x05F0)
class UGE_ShadowBombLoop_C final : public UGameplayEffect
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GE_ShadowBombLoop_C">();
	}
	static class UGE_ShadowBombLoop_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_ShadowBombLoop_C>();
	}
};

}

