#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GE_Trap_PoisonDarts_Dot

#include "Basic.hpp"

#include "GET_DirectBluntDamage_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GE_Trap_PoisonDarts_Dot.GE_Trap_PoisonDarts_Dot_C
// 0x0000 (0x05F0 - 0x05F0)
class UGE_Trap_PoisonDarts_Dot_C final : public UGET_DirectBluntDamage_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GE_Trap_PoisonDarts_Dot_C">();
	}
	static class UGE_Trap_PoisonDarts_Dot_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_Trap_PoisonDarts_Dot_C>();
	}
};

}

