#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: IND_DamControl_04

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass IND_DamControl_04.IND_DamControl_04_C
// 0x0000 (0x0B10 - 0x0B10)
class AIND_DamControl_04_C final : public ABuildingProp
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"IND_DamControl_04_C">();
	}
	static class AIND_DamControl_04_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AIND_DamControl_04_C>();
	}
};

}

