#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: LeaveDialog

#include "Basic.hpp"

#include "LeaveDialog_classes.hpp"
#include "LeaveDialog_parameters.hpp"


namespace SDK
{

// Function LeaveDialog.LeaveDialog_C.OnMouseButtonDownTapToClose
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// const struct FPointerEvent&             MouseEvent                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// struct FEventReply                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FEventReply ULeaveDialog_C::OnMouseButtonDownTapToClose(const struct FGeometry& MyGeometry, const struct FPointerEvent& MouseEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LeaveDialog_C", "OnMouseButtonDownTapToClose");

	Params::LeaveDialog_C_OnMouseButtonDownTapToClose Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.MouseEvent = std::move(MouseEvent);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function LeaveDialog.LeaveDialog_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void ULeaveDialog_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LeaveDialog_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LeaveDialog.LeaveDialog_C.ExecuteUbergraph_LeaveDialog
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ULeaveDialog_C::ExecuteUbergraph_LeaveDialog(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LeaveDialog_C", "ExecuteUbergraph_LeaveDialog");

	Params::LeaveDialog_C_ExecuteUbergraph_LeaveDialog Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

