#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: NeoTilted_Planter_Rectangle

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass NeoTilted_Planter_Rectangle.NeoTilted_Planter_Rectangle_C
// 0x0000 (0x0B10 - 0x0B10)
class ANeoTilted_Planter_Rectangle_C final : public ABuildingProp
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"NeoTilted_Planter_Rectangle_C">();
	}
	static class ANeoTilted_Planter_Rectangle_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ANeoTilted_Planter_Rectangle_C>();
	}
};

}

