#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: NPCLeaderItemPedestal

#include "Basic.hpp"

#include "FortniteGame_structs.hpp"
#include "Engine_structs.hpp"
#include "FortniteUI_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass NPCLeaderItemPedestal.NPCLeaderItemPedestal_C
// 0x0020 (0x0328 - 0x0308)
class ANPCLeaderItemPedestal_C final : public AFortItemPreviewPedestal
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0308(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UArrowComponent*                        Arrow;                                             // 0x0310(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UFortQuestItemDefinition*               QuestToShow;                                       // 0x0318(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UFortItemDefinition*                    HeroItemDefinition;                                // 0x0320(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_NPCLeaderItemPedestal(int32 EntryPoint);
	void CameraChanged(EFrontEndCamera NewCamera, EFrontEndCamera OldCamera);
	void ReceiveBeginPlay();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"NPCLeaderItemPedestal_C">();
	}
	static class ANPCLeaderItemPedestal_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ANPCLeaderItemPedestal_C>();
	}
};

}

