#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: Recreation_SportingGoods_Soccerball

#include "Basic.hpp"

#include "PhysicsBall_Master_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass Recreation_SportingGoods_Soccerball.Recreation_SportingGoods_Soccerball_C
// 0x0010 (0x0818 - 0x0808)
class ARecreation_SportingGoods_Soccerball_C final : public APhysicsBall_Master_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_Recreation_SportingGoods_Soccerball_C; // 0x0808(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class USoundBase*                             Ball_Hit_Sound;                                    // 0x0810(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_Recreation_SportingGoods_Soccerball(int32 EntryPoint);
	void BndEvt__SphereCollision_K2Node_ComponentBoundEvent_4_ComponentBeginOverlapSignature__DelegateSignature(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const struct FHitResult& SweepResult);
	void Reset_Ball_Hit_Sound();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Recreation_SportingGoods_Soccerball_C">();
	}
	static class ARecreation_SportingGoods_Soccerball_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ARecreation_SportingGoods_Soccerball_C>();
	}
};

}

