#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: ReportPlayerImageSettings

#include "Basic.hpp"

#include "UMG_structs.hpp"


namespace SDK
{

// UserDefinedStruct ReportPlayerImageSettings.ReportPlayerImageSettings
// 0x0050 (0x0050 - 0x0000)
struct FReportPlayerImageSettings final
{
public:
	TSoftObjectPtr<class UTexture2D>              Image_2_176A4DD44E5F69679DDE39965E03704E;          // 0x0000(0x0028)(Edit, BlueprintVisible, HasGetValueTypeHash)
	struct FWidgetTransform                       Transform_6_0ABF984F410C372270350888D0E52882;      // 0x0028(0x001C)(Edit, BlueprintVisible, NoDestructor)
	uint8                                         Pad_44[0x4];                                       // 0x0044(0x0004)(Fixing Size After Last Property [ Dumper-8 ])
	class UWidgetAnimation*                       Animation_9_8C60965D44F774A4EB449AA4BA6640FB;      // 0x0048(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

}

