#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: SK_Pickaxe_Jackel_AnimBP

#include "Basic.hpp"


namespace SDK::Params
{

// Function SK_Pickaxe_Jackel_AnimBP.SK_Pickaxe_Jackel_AnimBP_C.ExecuteUbergraph_SK_Pickaxe_Jackel_AnimBP
// 0x0004 (0x0004 - 0x0000)
struct SK_Pickaxe_Jackel_AnimBP_C_ExecuteUbergraph_SK_Pickaxe_Jackel_AnimBP final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

}

