#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: UIMapManagerAthena

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass UIMapManagerAthena.UIMapManagerAthena_C
// 0x0008 (0x0558 - 0x0550)
class AUIMapManagerAthena_C final : public AFortInGameMapManagerAthena
{
public:
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0550(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"UIMapManagerAthena_C">();
	}
	static class AUIMapManagerAthena_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AUIMapManagerAthena_C>();
	}
};

}

